---
development:
  cloud_name: stefank9
  api_key: '654472785677483'
  api_secret: tlzw-o7uCuSkrkwl9F38qK040sU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: stefank9
  api_key: '654472785677483'
  api_secret: tlzw-o7uCuSkrkwl9F38qK040sU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: stefank9
  api_key: '654472785677483'
  api_secret: tlzw-o7uCuSkrkwl9F38qK040sU
  enhance_image_tag: true
  static_image_support: false
